export const ROUTES = {
  HOME: '/homePage',
  LOGIN: '/login',
  CHAT: '/chat',
  CHAT_ROOM: '/chat/:id',
  ACCOUNT: '/accountPage',
  CONTACTS: '/contacts',
  NOTIFICATIONS: '/notif',
  CALL: '/call',
  PERSONAL: '/personal',
  GROUPS: '/groups',
  CHANNELS: '/channels',
  SETTINGS_ACCOUNT: '/accountPage/account',
  SETTINGS_PROFILE: '/accountPage/profile',
  SETTINGS_PASSWORD: '/accountPage/password',
  SETTINGS_NOTIFICATIONS: '/accountPage/notifications',
  SETTINGS_PRIVACY: '/accountPage/privacy',
  SETTINGS_DATA: '/accountPage/data',
  SETTINGS_CHAT: '/accountPage/chat',
  SETTINGS_STICKERS: '/accountPage/stickers',
  SETTINGS_FOLDERS: '/accountPage/folders',
  SETTINGS_DEVICES: '/accountPage/devices',
  SETTINGS_LANGUAGE: '/accountPage/language',
  SETTINGS_HELP: '/accountPage/help',
  SETTINGS_PREMIUM: '/accountPage/premium',
  SETTINGS_BUSINESS: '/accountPage/business',
};

export const PUBLIC_ROUTES = [ROUTES.LOGIN];
