export const AUTH_ACTIONS = {
  LOGIN_START: 'AUTH/LOGIN_START',
  LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
  LOGIN_FAILURE: 'AUTH/LOGIN_FAILURE',
  LOGOUT: 'AUTH/LOGOUT',
  SET_USER: 'AUTH/SET_USER',
  REFRESH_TOKEN: 'AUTH/REFRESH_TOKEN',
};

export const CHAT_ACTIONS = {
  SET_CONVERSATIONS: 'CHAT/SET_CONVERSATIONS',
  SET_ACTIVE_CHAT: 'CHAT/SET_ACTIVE_CHAT',
  ADD_CONVERSATION: 'CHAT/ADD_CONVERSATION',
  ADD_MESSAGE: 'CHAT/ADD_MESSAGE',
  SET_MESSAGES: 'CHAT/SET_MESSAGES',
  SET_TYPING: 'CHAT/SET_TYPING',
  MARK_READ: 'CHAT/MARK_READ',
  SET_LOADING: 'CHAT/SET_LOADING',
};

export const THEME_ACTIONS = {
  TOGGLE: 'THEME/TOGGLE',
  SET: 'THEME/SET',
};
